[versions]
guice = "7.0.0"
byte-buddy = "1.18.3"
jmock = "2.13.1"
junit-jupiter = "6.0.1"

[libraries]
guice = { module = "com.google.inject:guice", version.ref = "guice" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
jmock-junit5 = { module = "org.jmock:jmock-junit5", version.ref = "jmock" }
jmock-imposters = { module = "org.jmock:jmock-imposters", version.ref = "jmock" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[bundles]
jmock = ["byte-buddy", "jmock-junit5", "jmock-imposters"]
